name: Launch Python Web App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-launch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Optional: Run tests here if you have any
      # - name: Run tests
      #   run: pytest

      - name: Run main.py (background, for demonstration)
        run: |
          nohup python main.py &
          sleep 10
          # Add any checks here, e.g. curl http://localhost:5000

      - name: Show running processes (for debug)
        run: ps aux | grep python

      # Note: GitHub Actions runners are temporary, so your site will not stay up after the job ends.
